{% set name = "dnest4" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00a2bd651c931f2b007c948ac4c940ed0946926910384c7954d45d106a8afca5

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - dnest4

about:
  home: https://github.com/eggplantbren/DNest4
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Diffusive Nested Sampling'
  description: |
    DNest4 is a C++11 implementation of Diffusive Nested Sampling,
    a Markov Chain Monte Carlo (MCMC) algorithm for Bayesian
    Inference and Statistical Mechanics.
  doc_url: https://github.com/eggplantbren/DNest4
  dev_url: https://github.com/eggplantbren/DNest4

extra:
  recipe-maintainers:
    - dfm
